In [2]:
print("Hola, Python está funcionando correectamente")

a=30
b=20
resultado = a+b
print(f"El resultado de la suma es: {resultado}")

Hola, Python está funcionando correectamente
El resultado de la suma es: 50

In [3]:
import pandas as pd

url = "https://raw.githubusercontent.com/ElenaVillano/databases/refs/heads/main/db_falsas_alarmas.csv"

df = pd.read_csv(url)

## 1.- Estructura de la base de datos

En esta sección se realiza una exploración inicial de la base de datos de incidentes reportados al C5 de la Ciudad de México

In [4]:
print(df.head())

               folio  fecha_hora_creacion    fecha_hora_cierre  \
0  C5/20220923/04016  2022-09-23 18:38:34  2022-09-23 22:22:27
1  C5/20220829/00630  2022-08-29 02:56:31  2022-08-29 06:04:53
2  C5/20220724/01907  2022-07-24 04:29:09  2022-07-24 07:36:49
3  C5/20240215/03071  2024-02-15 16:20:03  2024-02-15 20:52:19
4  C5/20221006/03493  2022-10-06 19:33:05  2022-10-06 22:37:08

  tipo_incidente_c4           incidente_c4         alcaldia_inicio  \
0         Accidente  Choque sin lesionados     VENUSTIANO CARRANZA
1         Accidente           Motociclista              CUAUHTEMOC
2         Accidente  Choque sin lesionados              IZTAPALAPA
3         Accidente  Choque sin lesionados  LA MAGDALENA CONTRERAS
4         Accidente  Choque sin lesionados              IZTAPALAPA

  codigo_cierre  clas_con_f_alarma     tipo_entrada         alcaldia_cierre  \
0             A         EMERGENCIA  LLAMADA DEL 911     VENUSTIANO CARRANZA
1             A  URGENCIAS MEDICAS  LLAMADA DEL 911              CUAUHTEMOC
2             A         EMERGENCIA  LLAMADA DEL 911              IZTAPALAPA
3             A         EMERGENCIA  LLAMADA DEL 911  LA MAGDALENA CONTRERAS
4             F         EMERGENCIA  LLAMADA DEL 911              IZTAPALAPA

        alcaldia_catalogo             colonia_catalogo   longitud    latitud
0     Venustiano Carranza              20 De Noviembre -99.108352  19.443920
1              Cuauhtémoc                       Obrera -99.140843  19.416669
2              Iztapalapa         San Andres Tetepilco -99.130702  19.371340
3  La Magdalena Contreras                      La Cruz -99.233973  19.305985
4              Iztapalapa  Santa Martha Acatitla Norte -99.013140  19.374476

In [5]:
# Dimensiones de la base de datos
print("Número de registros:", df.shape[0])
print("Número de variables:", df.shape[1])

# Nombres de las variables
print("\nNombres de las variables:")
for i, columna in enumerate(df.columns, start=1):
    print(f"{i}. {columna}")

Número de registros: 124261
Número de variables: 14

Nombres de las variables:
1. folio
2. fecha_hora_creacion
3. fecha_hora_cierre
4. tipo_incidente_c4
5. incidente_c4
6. alcaldia_inicio
7. codigo_cierre
8. clas_con_f_alarma
9. tipo_entrada
10. alcaldia_cierre
11. alcaldia_catalogo
12. colonia_catalogo
13. longitud
14. latitud

In [ ]:
# Dimensiones de la base de datos
print("Número de registros:", df.shape[0])
print("Número de variables:", df.shape[1])

# Nombres de las variables
print("\nNombres de las variables:")
for i, columna in enumerate(df.columns, start=1):
    print(f"{i}. {columna}")

Número de registros: 124261
Número de variables: 14

Nombres de las variables:
1. folio
2. fecha_hora_creacion
3. fecha_hora_cierre
4. tipo_incidente_c4
5. incidente_c4
6. alcaldia_inicio
7. codigo_cierre
8. clas_con_f_alarma
9. tipo_entrada
10. alcaldia_cierre
11. alcaldia_catalogo
12. colonia_catalogo
13. longitud
14. latitud

In [7]:
import numpy as np

In [9]:
df.shape

(124261, 14)

In [10]:
df.columns

Index(['folio', 'fecha_hora_creacion', 'fecha_hora_cierre',
       'tipo_incidente_c4', 'incidente_c4', 'alcaldia_inicio', 'codigo_cierre',
       'clas_con_f_alarma', 'tipo_entrada', 'alcaldia_cierre',
       'alcaldia_catalogo', 'colonia_catalogo', 'longitud', 'latitud'],
      dtype='str')

In [11]:
df['fecha_hora_creacion'].value_counts()

fecha_hora_creacion
2023-10-21 14:45:51    2
2023-12-03 17:42:18    2
2022-04-10 17:30:28    2
2023-11-18 23:21:46    2
2023-12-02 16:58:12    2
                      ..
2022-12-05 11:12:02    1
2022-10-29 11:09:14    1
2023-10-10 14:29:48    1
2023-05-16 11:29:35    1
2022-11-14 19:38:46    1
Name: count, Length: 124106, dtype: int64

In [12]:
df.dtypes

folio                      str
fecha_hora_creacion        str
fecha_hora_cierre          str
tipo_incidente_c4          str
incidente_c4               str
alcaldia_inicio            str
codigo_cierre              str
clas_con_f_alarma          str
tipo_entrada               str
alcaldia_cierre            str
alcaldia_catalogo          str
colonia_catalogo           str
longitud               float64
latitud                float64
dtype: object

In [13]:
# Variables numéricas: pandas las detecta como int o float
vars_numericas = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Variables categóricas: pandas las detecta como 'str' 
vars_categoricas = df.select_dtypes(include='str').columns.tolist()

In [14]:
vars_categoricas

['folio',
 'fecha_hora_creacion',
 'fecha_hora_cierre',
 'tipo_incidente_c4',
 'incidente_c4',
 'alcaldia_inicio',
 'codigo_cierre',
 'clas_con_f_alarma',
 'tipo_entrada',
 'alcaldia_cierre',
 'alcaldia_catalogo',
 'colonia_catalogo']

In [15]:
vars_numericas

['longitud', 'latitud']

In [ ]:
def analizar_categoricas(df, columnas):
    

    resultados = []

    for columna in columnas:

        frecuencias = df[columna].value_counts()

        resultado = {
            "variable": columna,
            "n_categorias": df[columna].nunique(),
            "n_faltantes": df[columna].isnull().sum(),
            "moda": frecuencias.index[0],
            "top_2": frecuencias.index[1] if len(frecuencias) > 1 else "-",
            "top_3": frecuencias.index[2] if len(frecuencias) > 2 else "-"
        }

        resultados.append(resultado)

    return pd.DataFrame(resultados)

In [17]:
analizar_categoricas(df, vars_categoricas)

,variable,n_categorias,n_faltantes,moda,top_2,top_3
0,folio,124261,0,C5/20220923/04016,C5/20220829/00630,C5/20220724/01907
1,fecha_hora_creacion,124106,0,2023-10-21 14:45:51,2023-12-03 17:42:18,2022-04-10 17:30:28
2,fecha_hora_cierre,107462,0,2023-11-04 19:33:22,2023-10-30 15:02:48,2023-12-26 20:02:40
3,tipo_incidente_c4,7,0,Accidente,Lesionado,Cadáver
4,incidente_c4,16,0,Choque sin lesionados,Choque con lesionados,Atropellado
5,alcaldia_inicio,16,8,IZTAPALAPA,GUSTAVO A. MADERO,CUAUHTEMOC
6,codigo_cierre,4,0,D,A,F
7,clas_con_f_alarma,5,0,URGENCIAS MEDICAS,EMERGENCIA,DELITO
8,tipo_entrada,7,0,LLAMADA DEL 911,BOTÓN DE AUXILIO,RADIO
9,alcaldia_cierre,16,8,IZTAPALAPA,GUSTAVO A. MADERO,CUAUHTEMOC
10,alcaldia_catalogo,16,130,Iztapalapa,Gustavo A. Madero,Cuauhtémoc
11,colonia_catalogo,1373,2718,Centro,Agricola Oriental,Agricola Pantitlan

In [19]:
df[vars_numericas].describe()

            longitud        latitud
count  124261.000000  124261.000000
mean      -99.134031      19.381444
std         0.061571       0.071538
min       -99.352914      19.094877
25%       -99.174500      19.332895
50%       -99.136941      19.383000
75%       -99.092380      19.434346
max       -98.947940      19.632201

In [20]:
df.columns

Index(['folio', 'fecha_hora_creacion', 'fecha_hora_cierre',
       'tipo_incidente_c4', 'incidente_c4', 'alcaldia_inicio', 'codigo_cierre',
       'clas_con_f_alarma', 'tipo_entrada', 'alcaldia_cierre',
       'alcaldia_catalogo', 'colonia_catalogo', 'longitud', 'latitud'],
      dtype='str')

In [24]:
df.groupby("codigo_cierre")

In [25]:
df.groupby("codigo_cierre")["alcaldia_inicio"].value_counts()

codigo_cierre  alcaldia_inicio
A              IZTAPALAPA                6768
               CUAUHTEMOC                5934
               GUSTAVO A. MADERO         4971
               VENUSTIANO CARRANZA       3459
               BENITO JUAREZ             3369
                                         ...
I              BENITO JUAREZ               29
               AZCAPOTZALCO                24
               LA MAGDALENA CONTRERAS      22
               TLAHUAC                     22
               MILPA ALTA                  19
Name: count, Length: 64, dtype: int64

In [27]:
df.head()

,folio,fecha_hora_creacion,fecha_hora_cierre,tipo_incidente_c4,incidente_c4,alcaldia_inicio,codigo_cierre,clas_con_f_alarma,tipo_entrada,alcaldia_cierre,alcaldia_catalogo,colonia_catalogo,longitud,latitud
0,C5/20220923/04016,2022-09-23 18:38:34,2022-09-23 22:22:27,Accidente,Choque sin lesionados,VENUSTIANO CARRANZA,A,EMERGENCIA,LLAMADA DEL 911,VENUSTIANO CARRANZA,Venustiano Carranza,20 De Noviembre,-99.108352,19.443920
1,C5/20220829/00630,2022-08-29 02:56:31,2022-08-29 06:04:53,Accidente,Motociclista,CUAUHTEMOC,A,URGENCIAS MEDICAS,LLAMADA DEL 911,CUAUHTEMOC,Cuauhtémoc,Obrera,-99.140843,19.416669
2,C5/20220724/01907,2022-07-24 04:29:09,2022-07-24 07:36:49,Accidente,Choque sin lesionados,IZTAPALAPA,A,EMERGENCIA,LLAMADA DEL 911,IZTAPALAPA,Iztapalapa,San Andres Tetepilco,-99.130702,19.371340
3,C5/20240215/03071,2024-02-15 16:20:03,2024-02-15 20:52:19,Accidente,Choque sin lesionados,LA MAGDALENA CONTRERAS,A,EMERGENCIA,LLAMADA DEL 911,LA MAGDALENA CONTRERAS,La Magdalena Contreras,La Cruz,-99.233973,19.305985
4,C5/20221006/03493,2022-10-06 19:33:05,2022-10-06 22:37:08,Accidente,Choque sin lesionados,IZTAPALAPA,F,EMERGENCIA,LLAMADA DEL 911,IZTAPALAPA,Iztapalapa,Santa Martha Acatitla Norte,-99.013140,19.374476

In [ ]:
# Dimensiones de la base de datos
print("Número de registros:", df.shape[0])
print("Número de variables:", df.shape[1])

# Nombres de las variables
print("\nNombres de las variables:")
for i, columna in enumerate(df.columns, start=1):
    print(f"{i}. {columna}")

Número de registros: 124261
Número de variables: 14

Nombres de las variables:
1. folio
2. fecha_hora_creacion
3. fecha_hora_cierre
4. tipo_incidente_c4
5. incidente_c4
6. alcaldia_inicio
7. codigo_cierre
8. clas_con_f_alarma
9. tipo_entrada
10. alcaldia_cierre
11. alcaldia_catalogo
12. colonia_catalogo
13. longitud
14. latitud

In [34]:
df.dtypes

folio                             str
fecha_hora_creacion               str
fecha_hora_cierre      datetime64[us]
tipo_incidente_c4                 str
incidente_c4                      str
alcaldia_inicio                   str
codigo_cierre                     str
clas_con_f_alarma                 str
tipo_entrada                      str
alcaldia_cierre                   str
alcaldia_catalogo                 str
colonia_catalogo                  str
longitud                      float64
latitud                       float64
Fecha_hora_creacion    datetime64[us]
dtype: object

In [35]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

5.1. Contexto y estructura 
¿Qué fenómeno registra la base? Las llamadas recibidas al Centro de Comando, Control, Cómputo, Comunicaciones y Contacto Ciudadano de la Ciudad de México (C5) por incidentes viales regresitrados e la Ciudad de México.

 ¿Quién la produjo y con qué propósito? El gobierno de la Ciudad de México, con el objetivo de identificar los accidentes viales más frecuentes y los lugares donde más se producen.

¿Cuántas filas y columnas tiene?

In [36]:
# Dimensiones de la base de datos
print("Número de registros:", df.shape[0])
print("Número de variables:", df.shape[1])

# Nombres de las variables
print("\nNombres de las variables:")
for i, columna in enumerate(df.columns, start=1):
    print(f"{i}. {columna}")

Número de registros: 124261
Número de variables: 15

Nombres de las variables:
1. folio
2. fecha_hora_creacion
3. fecha_hora_cierre
4. tipo_incidente_c4
5. incidente_c4
6. alcaldia_inicio
7. codigo_cierre
8. clas_con_f_alarma
9. tipo_entrada
10. alcaldia_cierre
11. alcaldia_catalogo
12. colonia_catalogo
13. longitud
14. latitud
15. fecha_hora_creacion

¿Qué significa cada variable? Descríbanla con sus propias palabras, apoyándose en el diccionario de datos.

folio: Número de identificación de la llamada al C5.
fecha_hora_creacion: Hora de recepción de la llamada.
fecha_hora_cierre: Hora en que se termino de atender la emergencia reportada.
tipo de incidente_c4: Naturaleza de la emergencia reportada.
incidente_c4: Espicifación de los involucrados en el tipo de incidente.
alcaldia_inicio: Alcaldía donde se reportó e inició el seguimiento del incidente.
codigo_cierre: Identificador asignado cuando se termina la atención a la emergencia, dependiendo si fue un caso falso o no.
clas_con_f_alarma: Clasificación del tipo de emergencia.
tipo_entrada: Medio por el cual se recibió la notificación de la emergencia.
alcaldia_cierre: Alcaldía donde se terminó el seguimiento de la emergencia reportada.
alcaldia_catalogo: Alcaldía donde sucedió la emergencia.
colonia_catalogo: Colonia donde suceció la emergencia.
longitud: Punto georeferencial del incidente.
latitud: Punto georeferencial del incidente.
fecha_hora_creacion: Fecha de creación del reporte

5.3. Tipos, calidad y limpieza
Identifiquen tipos de datos y valores faltantes.

In [37]:
df.dtypes

folio                             str
fecha_hora_creacion               str
fecha_hora_cierre      datetime64[us]
tipo_incidente_c4                 str
incidente_c4                      str
alcaldia_inicio                   str
codigo_cierre                     str
clas_con_f_alarma                 str
tipo_entrada                      str
alcaldia_cierre                   str
alcaldia_catalogo                 str
colonia_catalogo                  str
longitud                      float64
latitud                       float64
fecha_hora_creacion    datetime64[us]
dtype: object

In [43]:
df.isna().sum()

folio                     0
fecha_hora_creacion       0
fecha_hora_cierre         0
tipo_incidente_c4         0
incidente_c4              0
alcaldia_inicio           8
codigo_cierre             0
clas_con_f_alarma         0
tipo_entrada              0
alcaldia_cierre           8
alcaldia_catalogo       130
colonia_catalogo       2718
longitud                  0
latitud                   0
fecha_hora_creacion       0
dtype: int64

In [44]:
# Conteo de valores faltantes por columna
faltantes = df.isna().sum()

# También calculamos el porcentaje
pct_faltantes = (faltantes / len(df) * 100).round(2)

# Unimos en una tabla y filtramos solo las que sí tienen faltantes
tabla_faltantes = pd.DataFrame({
    'valores_faltantes': faltantes,
    'porcentaje_%': pct_faltantes
})


tabla_faltantes[tabla_faltantes['valores_faltantes'] > 0]

                   valores_faltantes  porcentaje_%
alcaldia_inicio                    8          0.01
alcaldia_cierre                    8          0.01
alcaldia_catalogo                130          0.10
colonia_catalogo                2718          2.19

Identifiquen posibles duplicados, categorías inconsistentes o coordenadas fuera del rango esperado, cuando aplique.

In [38]:
# Identificación de duplicados
duplicados = df.duplicated()

print("Total de registros:", len(df))
print("Registros completamente duplicados:", duplicados.sum())
print("Porcentaje de duplicados:", round(duplicados.mean() * 100, 2), "%")

# Mostrar duplicados
display(df[duplicados].head(10))

Total de registros: 124261
Registros completamente duplicados: 0
Porcentaje de duplicados: 0.0 %

Empty DataFrame
Columns: [folio, fecha_hora_creacion, fecha_hora_cierre, tipo_incidente_c4, incidente_c4, alcaldia_inicio, codigo_cierre, clas_con_f_alarma, tipo_entrada, alcaldia_cierre, alcaldia_catalogo, colonia_catalogo, longitud, latitud, fecha_hora_creacion]
Index: []

In [39]:

columnas_texto = df.select_dtypes(
    include=["object", "string", "category"]
).columns

print("Columnas de texto:")
print(columnas_texto.tolist())

Columnas de texto:
['folio', 'fecha_hora_creacion', 'tipo_incidente_c4', 'incidente_c4', 'alcaldia_inicio', 'codigo_cierre', 'clas_con_f_alarma', 'tipo_entrada', 'alcaldia_cierre', 'alcaldia_catalogo', 'colonia_catalogo']

In [41]:
#Latitud y longitud
lat = pd.to_numeric(df["latitud"], errors="coerce")
lon = pd.to_numeric(df["longitud"], errors="coerce")

In [42]:
# Detectar coordenadas fuera del rango aproximado
fuera_rango = (
    lat.notna() & lon.notna() &
    (
        ~lat.between(19.0, 19.6) |
        ~lon.between(-99.4, -98.9)
    )
)

print("Coordenadas fuera del rango:", fuera_rango.sum())
print("Coordenadas faltantes o no numéricas:",
      (lat.isna() | lon.isna()).sum())

display(df.loc[fuera_rango].head(10))

Coordenadas fuera del rango: 4
Coordenadas faltantes o no numéricas: 0

,folio,fecha_hora_creacion,fecha_hora_cierre,tipo_incidente_c4,incidente_c4,alcaldia_inicio,codigo_cierre,clas_con_f_alarma,tipo_entrada,alcaldia_cierre,alcaldia_catalogo,colonia_catalogo,longitud,latitud,fecha_hora_creacion
26129,C5/220401/01123,2022-04-01 17:56:02,2022-04-01 17:59:04,Mi Calle,Incidente de tránsito,NaN,F,FALSA ALARMA,APLICATIVOS,NaN,NaN,NaN,-99.021432,19.632201,2022-04-01 17:56:02
40950,C5/220401/01134,2022-04-01 17:56:25,2022-04-01 18:00:22,Mi Calle,Incidente de tránsito,NaN,F,FALSA ALARMA,APLICATIVOS,NaN,NaN,NaN,-99.021432,19.632201,2022-04-01 17:56:25
59997,C5/220401/01137,2022-04-01 17:56:28,2022-04-01 17:59:48,Mi Calle,Incidente de tránsito,NaN,F,FALSA ALARMA,APLICATIVOS,NaN,NaN,NaN,-99.021432,19.632201,2022-04-01 17:56:28
108069,C5/220401/01124,2022-04-01 17:56:05,2022-04-01 17:58:30,Mi Calle,Incidente de tránsito,NaN,F,FALSA ALARMA,APLICATIVOS,NaN,NaN,NaN,-99.021432,19.632201,2022-04-01 17:56:05

Revisen si las variables están representadas correctamente, especialmente fechas y horas.

In [ ]:
df[['fecha_hora_creacion', 'fecha_hora_cierre']].sample(10, random_state=123)

In [ ]:
df['Fecha_hora_creacion'] = pd.to_datetime(df['fecha_hora_creacion'] , errors='coerce')
df['fecha_hora_cierre'] = pd.to_datetime(df['fecha_hora_cierre'] , errors='coerce')

Hagan las conversiones necesarias y expliquen cada decisión.

5.4. Data Profiling o perfilado por tipo de variable

Categóricas: categorías, frecuencias y valores faltantes.

Numéricas: medidas descriptivas y valores extremos, si existen.

Temporales: fechas mínima y máxima, cobertura y granularidad.

In [47]:
print("--- Rango de Fechas ---")
min_date = df['fecha_hora_creacion'].min()
max_date = df['fecha_hora_cierre'].max()
print(f"Fecha mínima: {min_date}")
print(f"Fecha máxima: {max_date}")

--- Rango de Fechas ---
Fecha mínima: fecha_hora_creacion    2021-12-31 20:59:59
fecha_hora_creacion    2021-12-31 20:59:59
dtype: object
Fecha máxima: 2024-02-29 23:58:48

Bajo esta estructura, cada fila representa un registro de incidente, mientras que las columnas describen sus características, como la clasificación, la ubicación y la información temporal disponible.

Interpreten los resultados: no basta con imprimir tablas.